name: Make Release
on:
  push:
    tags:
    - '*'

env:
  REPOSITORY_NAME: GameOfLife
  FOLDER_NAME: sigma-axis

  TIME_ZONE: Asia/Tokyo
  # Time zone for the timestamp when releasing.

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Pack and compress
      run: |
        mkdir -p pack/zip
        mkdir -p pack/pkg/Script/${{ env.FOLDER_NAME }}
        mkdir -p pack/pkg/Language
        cp *.anm2 pack/pkg/Script/${{ env.FOLDER_NAME }}
        cp Languages/*.aul2 pack/pkg/Language
        cd pack/pkg
        zip -r ../zip/${{ env.REPOSITORY_NAME }}.au2pkg.zip *
        cd ../..
        cp *.md pack/zip
        cp LICENSE pack/zip/LICENSE
        cd pack/zip
        zip -r ../../aviutl2_script_${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.zip *
      # rename .zip file for downloading if necessary.

    - name: Prepare release notes
      id: release-notes
      run: |
        echo "name=${{ github.ref_name }} ($(TZ='${{ env.TIME_ZONE }}' date +'%Y-%m-%d'))" >> $GITHUB_OUTPUT
        echo "### 更新内容" >> ReleaseNotes.txt
        phase=0
        IFS=$'\n'
        cat pack/README.md | while read line; do
          if [[ $phase == 0 ]]; then
            if [[ $line =~ ^##*[[:space:]]{1,}'改版履歴'[[:space:]]*$ ]]; then phase=1; fi
          elif [[ $phase == 1 ]]; then
            if [[ $line =~ ^-[[:space:]] ]]; then phase=2; fi
          elif [[ $line =~ ^(-|##*)[[:space:]] ]]; then break
          else
            echo ${line:2} >> ReleaseNotes.txt
          fi
        done

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.release-notes.outputs.name }}
        files: '*.zip'
        body_path: ReleaseNotes.txt
